import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Flair Hijab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>  
          <img />
          <a href='/'>Home</a>
          <a href='/products'>Products</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((pr) => ( <a key={pr.id} href={`/products/${pr.id}`}> <Image alt={pr.title} width={300} height={300} src={pr.image}/> <h2>{pr.title}</h2><p>{pr.description}</p> </a>))}

      </main>

      <footer className={styles.footer}></footer>
    </>
  )
}

export async function getServerSideProps() {
  const {products_categories} = await import('/data/data.json');
    return {
        props:{
            data: products_categories,
        },
    };
}